config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'dogs#index'
  resources :dogs

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user
  has_attached_file :image, :styles => { :medium =>"400x300>", :thumb => "290x290>" }
  validates_attachment_content_type :image,:content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :dogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [ :edit, :update, :destroy]
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    #@dogs = Dog.all
    @dogs = current_user.dogs
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
    @dog = current_user.dogs.build
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)
    @dog = current_user.dogs.build(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :sex, :breed_of_dog, :birthday, :image, :description)
    end
  def correct_user
    @dog = current_user.dogs.find_by(id: params[:id])
    redirect_to dogs_path, notice: "Nie jesteś uprawniony do edycji" if @dog.nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_form.html.erb
<%= form_for dog, html: { multipart: true } do |f| %>
<%= form_with(model: dog, local: true) do |form| %>

  <% if dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% dog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container" style="width: 30%; margin-left: auto; margin-right: auto">
  <div class="panel panel-default devise-bs">
  <div class="panel-heading">
    Imię<br/>
    <%= form.text_field :name %>
  </div>

  <div class="panel-heading">
    Płeć<br/>
    <%= form.text_field :sex %>
  </div>

  <div class="panel-heading">
    Rasa psa<br/>
    <%= form.text_field :breed_of_dog %>
  </div>

  <div class="panel-heading">
    Data narodzin<br/>
    <%= form.date_select :birthday %>
  </div>

  <div class="panel-heading">
    Opis<br/>
    <%= form.text_area :description %>
  </div>
    <div class="panel-heading">
      <%= f.label :image, "Obraz" %><br/>
      <%= f.file_field :image, class: "form-control"%>
    </div>

  <div class="actions">
    <%= link_to 'Powrót', dogs_path, class: 'btn btn-default', style:'float:right;margin:25px' %>
    <%= form.submit 'Zapisz', class:'btn btn-success', style:'float:right;margin:25px' %>

<% end %>
<% end %>
</div>
</div>
</div>
</div>

app/views/dogs/edit.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <nav class="navbar navbar-default">
    <div class="sitename" style="float: left; margin-left: 25px">
      <h3> Edytujesz informacje o psie:  <%= @dog.name %></h3>
    </div>
    <div class="container-fluid">

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Dodaj psa", new_dog_path %></li>
        <li><%= link_to "Edytuj profil", edit_user_registration_path %></li>
        <li><%= link_to "Wyloguj się", destroy_user_session_path, method: :delete %></li>

        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

<%= render 'form', dog: @dog %>

app/views/dogs/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <nav class="navbar navbar-default">
    <div class="sitename" style="float: left; margin-left: 25px">
      <h3> Twoje Psy</h3>
    </div>
    <div class="container-fluid">

        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Dodaj psa", new_dog_path %></li>
          <li><%= link_to "Edytuj profil", edit_user_registration_path %></li>
          <li><%= link_to "Wyloguj się", destroy_user_session_path, method: :delete %></li>

          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

</nav>
</div>
<div class="container">
<div class="jumbotron" style="background-color: white; border: 0px" >
<div class="container-fluid">
  <div class="row">
    <% @dogs.each do |dog| %>
    <div class="d-flex flex-row bd-highlight mb-2" style="text-align: center" >
      <div class="col-xs-6 col-md-3" style="background-color: #EFEFEF ;  margin:5px; height: 310px; padding: 15px; border-radius: 15px; margin-left: 5%" >

            <%= image_tag dog.image.url(:thumb), style:'width: 100%;  height:180px; overflow:hidden; border-radius:15px' %>

        <div class="caption">
         <h2><%= dog.name %><h2>
        </div>
            <%= link_to 'Pokaż', dog, class: 'btn btn-primary'  %>
            <%= link_to 'Edytuj', edit_dog_path(dog), class: 'btn btn-default'  %>
            <%= link_to 'Usuń', dog, method: :delete, data: { confirm: 'Napewno chcesz usunąć?' }, class: 'btn btn-danger'  %>
      </div>
     </div>
    <% end %>
   </div>

  </div>
</div>
</div>

app/views/dogs/new.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<nav class="navbar navbar-default">
  <div class="sitename" style="float: left; margin-left: 25px">
    <h3> Nowy pies</h3>
  </div>
  <div class="container-fluid">

    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Edytuj profil", edit_user_registration_path %></li>
      <li><%= link_to "Wyloguj się", destroy_user_session_path, method: :delete %></li>

      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= render 'form', dog: @dog %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>
<p id="notice"><%= notice %></p>
<div class="container">
  <nav class="navbar navbar-default">
    <div class="sitename" style="float: left; margin-left: 25px">
      <h3> Twój pies</h3>
    </div>
    <div class="container-fluid">

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Dodaj psa", new_dog_path %></li>
        <li><%= link_to "Edytuj profil", edit_user_registration_path %></li>
        <li><%= link_to "Wyloguj się", destroy_user_session_path, method: :delete %></li>

        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>
<div class="container">
  <div class="container-fluid" style="max-width: 75%; background-color: #F7F7F7; border-radius:20px">
    <div class="image" style="float:left; margin:20px">
        <%= image_tag @dog.image.url(:medium), style:'border-radius:20px' %>
    </div>
    <div class="name" style="font-size: 45px">
      <%= @dog.name %>
    </div>
    <div class="info" style="font-size: 20px">
      <div class="sex" style=" ; margin:10px">
        <strong>Płeć:</strong>
         <%= @dog.sex %>
       </div>
      <div class="sex" style="  margin:10px">
         <strong>Rasa psa:</strong>
           <%= @dog.breed_of_dog %>
      </div>

      <div class="sex" style=" margin:10px">
        <strong>Data urodzenia:</strong>
           <%= @dog.birthday %>
      </div>

    <div class="sex" style="  margin:10px">
         <strong>Opis:</strong>
           <%= @dog.description %>
    </div>
    </div>
<div class="btn" style="float: right">
      <%= link_to 'Zmień', edit_dog_path(@dog), class:'btn btn-primary' %>
      <%= link_to 'Powrót', dogs_path, class:'btn btn-default'%>
</div>
</div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyDogs2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  <% if user_signed_in? %>
    <p><%= link_to "Wyloguj się", destroy_user_session_path, method: :delete %></p>
    <% end %>
  </body>
</html>